[package]
name = "service-status"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"

[[bin]]
name = "sys-stat"
path = "src/main.rs"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
dirs = "3.0"
